// vi: ft=groovy

node { // <1>

    stage('Setup Tools') { // <2>
        echo 'Setup Tools' // <3>
        env.PYENV_VERSION = "{% raw %}{{ pyenv_version }}{% endraw %}"
        env.PYENV_ROOT = "${env.HOME}/.pyenv"
        env.PATH = "${env.PYENV_ROOT}/shims:${env.PYENV_ROOT}/bin:/usr/local/bin:${env.PATH}"
        checkout scm
        sh "./ci/jenkins-pyenv-install.sh ${env.PYENV_VERSION}"
        sh "pyenv versions"
        sh "pyenv which python"
        sh "pip install --upgrade pip"
        sh "pip install --upgrade tox"
        sh "tox"
    }
    
    stage('Build') { // <2>
        echo 'Build' // <3>
    }

    stage('Test') {
        echo 'Test' // <4>
    }

    stage('Deploy') {
        echo 'Deploy'
    }
}

