// vi: ft=groovy

node { // <1>

    stage('Setup Tools') { // <2>
        echo 'Setup Tools' // <3>
        env.PYENV_VERSION = "3.5.2"
        env.PYENV_ROOT = "${env.HOME}/.pyenv"
        env.PATH = "${env.PYENV_ROOT}/shims:${env.PYENV_ROOT}/bin:/usr/local/bin:${env.PATH}"
        sh "pyenv install -s ${env.PYENV_VERSION}; eval \"\$(pyenv init -)\"; pyenv shell ${env.PYENV_VERSION}"
        sh "pyenv which python"
        sh "pip install tox"
    }
    
    stage('Build') { // <2>
        echo 'Build' // <3>
    }

    stage('Test') {
        echo 'Test' // <4>
    }

    stage('Deploy') {
        echo 'Deploy'
    }
}
